### ISSUE TITLE
Setting number of jobs during spot extraction

### ISSUE THREAD

**Issue by bradleycolquitt** [JaneliaSciComp/multifish#1]
How do you specify the number of parallel jobs during spot extraction? I see that you can set the number of cpus per job, but it seems that it always runs the number of jobs equal to the total number of threads on my workstation. This is generally OK, but I use this machine for other analyses, and it'd be good to leave a little processing room. Thanks! And great job on this; it's running super well on some early EASI-FISH data.

**Comment by cgoina** [comment]
The number of parallel jobs is equal to the number of tiles generated for spot extraction, and this number is determined by these parameters: ' --spot_extraction_xy_stride', '--spot_extraction_xy_overlap', '--spot_extraction_z_stride',       
'--spot_extraction_z_overlap' and by the size of the volume. Keep in mind that if you use larger tiles - you may need to allocate more cpus and memory for the spot extraction job.
