### ISSUE TITLE
Hi ,I am testing this pipeline and would like you to provide some examples. I hope to get your help. I would really appreciate your support and help.

### ISSUE THREAD

**Issue by liyongxin123** [JaneliaSciComp/multifish#19]
Hi ,I am testing this pipeline and would like you to provide some examples. I hope to get your help. I would really appreciate your support and help.

**Comment by krokicki** [comment]
Hi @liyongxin123 ,

There are examples provided. You can run `examples/demo_tiny.sh` to have it download some test data and run the full pipeline on it. It's all documented here: https://janeliascicomp.github.io/multifish/QuickStart.html

Let us know if something is not working once you follow the instructions.

Best regards,
Konrad
