### ISSUE TITLE
Cannot do warp_spots:apply_transform separately 

### ISSUE THREAD

**Issue by neugun** [JaneliaSciComp/multifish#21]
Hi,

## Bug report 
I want to run warp_spots separately after extracted spots and the image registration, however, the warp_spots step was not executed if I skip registration and spot_extraction.

## Description of the problem
I want to run warp_spots separately after extracted spots and I submitted a job that skipped other steps (_skip: stitching,registration,spot_extraction,segmentation,warp_spots,measure_intensities,assign_spots_) at the nextflow tower. The warp_spots were not run but the job was marked as "completed". 

## Log file(s)

_Jul-19 18:58:57.461 [main] DEBUG nextflow.Session - Ignite dataflow network (65)
Jul-19 18:58:57.461 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > download
Jul-19 18:58:57.463 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:prepare_stitching_data
Jul-19 18:58:57.464 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:prepare_spark_work_dir
Jul-19 18:58:57.465 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:spark_master
Jul-19 18:58:57.465 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:wait_for_master
Jul-19 18:58:57.467 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:spark_worker
Jul-19 18:58:57.467 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:wait_for_worker
Jul-19 18:58:57.467 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_parse_czi_tiles:spark_start_app
Jul-19 18:58:57.467 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_czi2n5:spark_start_app
Jul-19 18:58:57.467 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_flatfield_correction:spark_start_app
Jul-19 18:58:57.467 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_retile:spark_start_app
Jul-19 18:58:57.470 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_stitching:spark_start_app
Jul-19 18:58:57.470 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_fuse:spark_start_app
Jul-19 18:58:57.470 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:terminate_stitching
Jul-19 18:58:57.475 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:prepare_spots_dirs
Jul-19 18:58:57.475 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:prepare_spark_work_dir
Jul-19 18:58:57.475 [Actor Thread 1] DEBUG nextflow.Nextflow - Spot extraction results: []
Jul-19 18:58:57.476 [Actor Thread 2] DEBUG nextflow.Nextflow - Extracted spots to warp: [null, null, null]
Jul-19 18:58:57.482 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:spark_master
Jul-19 18:58:57.482 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:wait_for_master
Jul-19 18:58:57.482 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:spark_worker
Jul-19 18:58:57.483 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:wait_for_worker
Jul-19 18:58:57.483 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:run_rsfish:spark_start_app
Jul-19 18:58:57.483 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:terminate_rsfish
Jul-19 18:58:57.486 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:postprocess_spots
Jul-19 18:58:57.486 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > segmentation:predict
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:cut_tiles
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:fixed_coarse_spots
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:moving_coarse_spots
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:coarse_ransac
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:apply_transform_at_aff_scale
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:apply_transform_at_def_scale
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:fixed_spots
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:moving_spots
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:ransac_for_tile
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:interpolate_affines
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:deform
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:stitch
Jul-19 18:58:57.487 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:final_transform
Jul-19 18:58:57.488 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > collect_merge_points:collect_merged_points_files
Jul-19 18:58:57.491 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > warp_spots:apply_transform
Jul-19 18:58:57.494 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > measure_intensities
Jul-19 18:58:57.497 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > assign_spots
Jul-19 18:58:57.497 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > publish
Jul-19 18:58:57.497 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Jul-19 18:58:57.497 [main] DEBUG nextflow.Session - Session await
Jul-19 18:58:57.502 [Actor Thread 14] DEBUG nextflow.Nextflow - Expected registration for warping spots: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c0, s2]
Jul-19 18:58:57.502 [Actor Thread 14] DEBUG nextflow.Nextflow - Expected registration for warping spots: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c1, s2]
Jul-19 18:58:57.507 [Actor Thread 14] DEBUG nextflow.Nextflow - Expected registration for warping spots: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c3, s2]
Jul-19 18:58:57.572 [Actor Thread 8] DEBUG nextflow.Nextflow - Fixed registration input: [LHA_5_R2_4x4, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching]
Jul-19 18:58:57.602 [Actor Thread 9] DEBUG nextflow.Nextflow - Registration results used for warping spots: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c0, s2]
Jul-19 18:58:57.603 [Actor Thread 9] DEBUG nextflow.Nextflow - Registration results used for warping spots: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c1, s2]
Jul-19 18:58:57.603 [Actor Thread 9] DEBUG nextflow.Nextflow - Registration results used for warping spots: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c3, s2]
Jul-19 18:58:57.605 [Actor Thread 3] DEBUG nextflow.Nextflow - Warped spots output for LHA_5_R10_4x4 to LHA_5_R2_4x4 -> /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/LHA_5_R10_4x4-to-LHA_5_R2_4x4
Jul-19 18:58:57.605 [Actor Thread 3] DEBUG nextflow.Nextflow - Registration result to be combined with extracted spots result: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c0, s2] -> [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, c0, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c0/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/LHA_5_R10_4x4-to-LHA_5_R2_4x4]
Jul-19 18:58:57.614 [Actor Thread 3] DEBUG nextflow.Nextflow - Warped spots output for LHA_5_R10_4x4 to LHA_5_R2_4x4 -> /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/LHA_5_R10_4x4-to-LHA_5_R2_4x4
Jul-19 18:58:57.614 [Actor Thread 3] DEBUG nextflow.Nextflow - Registration result to be combined with extracted spots result: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c1, s2] -> [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, c1, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c1/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/LHA_5_R10_4x4-to-LHA_5_R2_4x4]
Jul-19 18:58:57.614 [Actor Thread 3] DEBUG nextflow.Nextflow - Warped spots output for LHA_5_R10_4x4 to LHA_5_R2_4x4 -> /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/LHA_5_R10_4x4-to-LHA_5_R2_4x4
Jul-19 18:58:57.617 [Actor Thread 3] DEBUG nextflow.Nextflow - Registration result to be combined with extracted spots result: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/transform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/warped, c3, s2] -> [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, c3, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R2_4x4/stitching/export.n5, /c3/s2, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/registration/LHA_5_R10_4x4-to-LHA_5_R2_4x4/invtransform, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/LHA_5_R10_4x4-to-LHA_5_R2_4x4]
Jul-19 18:58:57.650 [Actor Thread 31] DEBUG nextflow.container.SingularityCache - Singularity found local store for image=docker://multifish/downloader:1.1.0; path=/home/zzhenggang/.singularity_cache/multifish-downloader-1.1.0.img
Jul-19 18:58:57.650 [Actor Thread 3] DEBUG nextflow.container.SingularityCache - Singularity found local store for image=docker://public.ecr.aws/janeliascicomp/multifish/registration:1.2.1; path=/home/zzhenggang/.singularity_cache/public.ecr.aws-janeliascicomp-multifish-registration-1.2.1.img
Jul-19 18:58:57.694 [Actor Thread 11] DEBUG nextflow.util.CacheHelper - Hash asset file sha-256: /data/tower/.nextflow/pipelines/3109d2bf/JaneliaSciComp/multifish/data-sets/segmentation.txt
Jul-19 18:58:57.698 [Actor Thread 11] DEBUG nextflow.util.CacheHelper - Hash asset file sha-256: /data/tower/.nextflow/pipelines/3109d2bf/JaneliaSciComp/multifish/bin/download_dataset.sh
Jul-19 18:58:57.803 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SLURM] submitted process collect_merge_points:collect_merged_points_files (1) > jobId: 16547; workDir: /data/tower/84/0ca9a41cfb8bf92e9191805ad6d2bf
Jul-19 18:58:57.804 [Task submitter] INFO  nextflow.Session - [84/0ca9a4] Submitted process > collect_merge_points:collect_merged_points_files (1)
[84/0ca9a4] Submitted process > collect_merge_points:collect_merged_points_files (1)
Jul-19 18:58:57.831 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SLURM] submitted process download (1) > jobId: 16548; workDir: /data/tower/2e/ea4a5d9020070c4e5158ddcfcc0aa7
Jul-19 18:58:57.831 [Task submitter] INFO  nextflow.Session - [2e/ea4a5d] Submitted process > download (1)
[2e/ea4a5d] Submitted process > download (1)
Jul-19 18:59:01.584 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 16547; id: 2; name: collect_merge_points:collect_merged_points_files (1); status: COMPLETED; exit: 0; error: -; workDir: /data/tower/84/0ca9a41cfb8bf92e9191805ad6d2bf started: 1658282341577; exited: 2022-07-20T01:58:58.512546Z; ]
Jul-19 18:59:01.606 [Actor Thread 4] DEBUG nextflow.Nextflow - Found /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c0.txt /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c1.txt /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c3.txt in /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots
Jul-19 18:59:01.606 [Actor Thread 7] DEBUG nextflow.Nextflow - Collected spots files [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c0.txt]
Jul-19 18:59:01.607 [Actor Thread 7] DEBUG nextflow.Nextflow - Collected spots files [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c1.txt]
Jul-19 18:59:01.607 [Actor Thread 7] DEBUG nextflow.Nextflow - Collected spots files [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c3.txt]
Jul-19 18:59:01.607 [Actor Thread 7] DEBUG nextflow.Nextflow - Existing spots file: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, null, s0, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c0.txt]
Jul-19 18:59:01.608 [Actor Thread 11] DEBUG nextflow.Nextflow - Extracted spots to warp: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, null, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c0.txt]
Jul-19 18:59:01.608 [Actor Thread 7] DEBUG nextflow.Nextflow - Existing spots file: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, null, s0, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c1.txt]
Jul-19 18:59:01.608 [Actor Thread 7] DEBUG nextflow.Nextflow - Existing spots file: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, null, s0, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c3.txt]
Jul-19 18:59:01.608 [Actor Thread 4] DEBUG nextflow.Nextflow - Extracted spots to warp: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, null, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c1.txt]
Jul-19 18:59:01.608 [Actor Thread 7] DEBUG nextflow.Nextflow - Extracted spots to warp: [/data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/stitching/export.n5, null, /data/sternsonlab/Zhenggang/Gary_analysis/outputs/LHA_5_R10_4x4/spots/spots_c3.txt]
Jul-19 18:59:01.631 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 16548; id: 1; name: download (1); status: COMPLETED; exit: 0; error: -; workDir: /data/tower/2e/ea4a5d9020070c4e5158ddcfcc0aa7 started: 1658282341623; exited: 2022-07-20T01:58:58.584548Z; ]
Jul-19 18:59:01.632 [main] DEBUG nextflow.Session - Session await > all process finished
Jul-19 18:59:01.637 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-19 18:59:01.642 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=2; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=9ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=1 GB; ]
Jul-19 18:59:01.642 [main] DEBUG nextflow.trace.TimelineObserver - Flow completing -- rendering html timeline
Jul-19 18:59:01.870 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jul-19 18:59:01.870 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-tower@1.4.0'
Jul-19 18:59:01.870 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-tower
Jul-19 18:59:01.910 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye_

### Environment 
* EASI-FISH Pipeline version: [1.0.0] 
* Nextflow version: [version 22.04.3]
* Container runtime: [Singularity]
* Platform: [slurm]
* Operating system: [Linux]

### Additional context

I am wondering if any of the other steps from the EASIFISH pipeline (e.g., spot_extraction) needs to be submitted and run with warp spots so that the step of warp spots can be launched? Many thanks!

Best
Zhenggang

**Comment by neugun** [comment]
Hi,

FYI, I found that DEBUG nextflow.Nextflow  -Extracted spots to warp are **null** after starting all the processes (see below log).  

**Jul-20 15:13:23.879 [Actor Thread 5] DEBUG nextflow.Nextflow  - Extracted spots to warp: [null, null, null]**

Jul-20 15:13:23.865 [main] DEBUG nextflow.Session - Ignite dataflow network (65)
Jul-20 15:13:23.866 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > download
Jul-20 15:13:23.867 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:prepare_stitching_data
Jul-20 15:13:23.867 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:prepare_spark_work_dir
Jul-20 15:13:23.867 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:spark_master
Jul-20 15:13:23.867 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:wait_for_master
Jul-20 15:13:23.867 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:spark_worker
Jul-20 15:13:23.868 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:spark_cluster:wait_for_worker
Jul-20 15:13:23.870 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_parse_czi_tiles:spark_start_app
Jul-20 15:13:23.872 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_czi2n5:spark_start_app
Jul-20 15:13:23.872 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_flatfield_correction:spark_start_app
Jul-20 15:13:23.872 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_retile:spark_start_app
Jul-20 15:13:23.872 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_stitching:spark_start_app
Jul-20 15:13:23.872 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:run_fuse:spark_start_app
Jul-20 15:13:23.872 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > stitching:stitch:terminate_stitching
Jul-20 15:13:23.878 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:prepare_spots_dirs
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:prepare_spark_work_dir
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:spark_master
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:wait_for_master
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:spark_worker
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:spark_cluster:wait_for_worker
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:run_rsfish:spark_start_app
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:terminate_rsfish
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > spot_extraction:rsfish:postprocess_spots
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > segmentation:predict
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:cut_tiles
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:fixed_coarse_spots
Jul-20 15:13:23.879 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:moving_coarse_spots
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:coarse_ransac
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:apply_transform_at_aff_scale
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:apply_transform_at_def_scale
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:fixed_spots
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:moving_spots
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:ransac_for_tile
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:interpolate_affines
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:deform
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:stitch
Jul-20 15:13:23.880 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > registration:final_transform
Jul-20 15:13:23.881 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > collect_merge_points:collect_merged_points_files
Jul-20 15:13:23.881 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > warp_spots:apply_transform
Jul-20 15:13:23.881 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > measure_intensities
Jul-20 15:13:23.882 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > assign_spots
Jul-20 15:13:23.882 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > publish
Jul-20 15:13:23.882 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Jul-20 15:13:23.882 [main] DEBUG nextflow.Session - Session await
**Jul-20 15:13:23.879 [Actor Thread 5] DEBUG nextflow.Nextflow - Extracted spots to warp: [null, null, null]**
Jul-20 15:13:23.879 [Actor Thread 7] DEBUG nextflow.Nextflow - Spot extraction results: []

I also confirmed that the warp_spots can be launched if I did not skip spot_extraction, and it will be executed after the spot extraction is finished. It would be great if we can run the warp_spots alone and make it not dependent on the spot_extraction step. 

Thanks!
Zhenggang

**Comment by cgoina** [comment]
warp spots does not depend on the the registration task or spot detection task being run but it depends on the data generated by those tasks to be there. The spots must exist and the warp matrix must exist as well. Could you confirm that the data existed?
