### ISSUE TITLE
error: registration:moving_coarse_spots, out of memory

### ISSUE THREAD

**Issue by vincentex97** [JaneliaSciComp/multifish#32]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

## Description of the problem
Running registration, segmentation, RS-FISH on two rounds of in-house acquired data.
Stitched images were all quality checked.
running with AWS Fsx, with 9.6TB (5.47TB left), 1920 MB/s throughput
Same out of memory error showed up for at least 4 times with different parameters used.

**error report:**
```
The exit status of the task that caused the workflow execution to fail was: 1

Error executing process > 'registration:moving_coarse_spots (1)'

Caused by:
  Essential container in task exited - OutOfMemoryError: Container killed due to memory usage

Command executed:

  umask 0002
  mkdir -p /fsx/work/outputs/dr2_sap2_r3/registration/dr2_sap2_r3-to-dr2_sap2_r2/aff
  /app/scripts/waitforpaths.sh /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3
  /entrypoint.sh spots coarse /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5 /c3/s3 /fsx/work/outputs/dr2_sap2_r3/registration/dr2_sap2_r3-to-dr2_sap2_r2/aff/moving_spots.pkl 8 2000

Command exit status:
  1

Command output:
  Checking for /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3

Command error:
  Checking for /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3
  /entrypoint.sh: line 5:   109 Killed                  python /app/bigstream/${SCRIPT_NAME}.py "$@"
  .command.run: line 156: kill: (43) - No such process

Work dir:
  /fsx/work/46/026cc3fbf7a51266dcd678e42ddfb9

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

Caused by:
  Essential container in task exited - OutOfMemoryError: Container killed due to memory usage

## Log file(s)

(Please attach relevant log files, including .nextflow.log and any process logs that had errors.)
`[a1/f4ccd3] Submitted process > download (1)
[61/3e6b28] Submitted process > spot_extraction:rsfish:prepare_spots_dirs (2)
[81/7568bd] Submitted process > spot_extraction:rsfish:prepare_spots_dirs (1)
[56/dfd162] Submitted process > registration:cut_tiles (1)
[7a/1ddfb9] Submitted process > spot_extraction:rsfish:spark_cluster:prepare_spark_work_dir
ERROR ~ Error executing process > 'registration:moving_coarse_spots (1)'
Caused by:
  Essential container in task exited - OutOfMemoryError: Container killed due to memory usage
Command executed:
  umask 0002
  mkdir -p /fsx/work/outputs/dr2_sap2_r3/registration/dr2_sap2_r3-to-dr2_sap2_r2/aff
  /app/scripts/waitforpaths.sh /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3
  /entrypoint.sh spots coarse /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5 /c3/s3 /fsx/work/outputs/dr2_sap2_r3/registration/dr2_sap2_r3-to-dr2_sap2_r2/aff/moving_spots.pkl 8 2000
Command exit status:
  1
Command output:
  Checking for /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3
Command error:
  Checking for /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3
  /entrypoint.sh: line 5:   109 Killed                  python /app/bigstream/${SCRIPT_NAME}.py "$@"
  .command.run: line 156: kill: (43) - No such process
Work dir:
  /fsx/work/46/026cc3fbf7a51266dcd678e42ddfb9
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
-- Check 'nf-1NLS9Es5Llg0pe.log' file for details
WARN: Killing running tasks (8)
WARN: Tower request field `workflow.errorMessage` exceeds expected size | offending value: `Checking for /fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3
/entrypoint.sh: line 5:   109 Killed                  python /app/bigstream/${SCRIPT_NAME}.py "$@"
/fsx/work/46/026cc3fbf7a51266dcd678e42ddfb9/.command.run: line 156: kill: (43) - No such process`, size: 264 (max: 255)
[AWS BATCH] Waiting jobs reaper to complete (4 jobs to be terminated)
Saving cache: .nextflow/cache/1d3a76db-9643-47aa-99ba-1dcdd84e7b04 => /fsx/work/.nextflow/cache/1d3a76db-9643-47aa-99ba-1dcdd84e7b04
General`

### Environment 

* EASI-FISH Pipeline version: [?] 
* Nextflow version: [?]
* Platform: AWS

### Additional context

(Add any other context about the problem here)

**Comment by vincentex97** [comment]
a follow-up on my reported issue. even though with upgraded storage on Fsx (12000GB), and reduce the memory requested, the pipeline still fails at the above mentioned step and also failed at segmentation prediction step for the same error type (out of memory)

**Comment by vincentex97** [comment]
Another follow-up of my previous issue. I tried to run the pipeline separately, segmentation v. registration v. rs-fish. Same issue happened again, with segmentation stuck at segmentation prediction (out of memory); registration stuck at moving-coarse-spot (out of memory).

`The exit status of the task that caused the workflow execution to fail was: 137

Error executing process > 'registration:moving_coarse_spots (1)'

Caused by:
  Essential container in task exited - OutOfMemoryError: Container killed due to memory usage'

**Comment by cgoina** [comment]
Have you tried with more memory for coarse spots? Pass in this parameter '--coarse_spots_memory 16G' - the current default for finding the spots is 8G. Are you using a different tile size (registration_xy_stride and registration_z_stride params)?

**Comment by vincentex97** [comment]
I tried to increase the memory for segmentation and coarse spots as follow:
`   coarse_spots_cpus = 6
   coarse_spots_memory = '20'
   segmentation_scale = 's2'
   segmentation_cpus = 10
   segmentation_memory = '100'`
still failed for the same reason.

**Comment by vincentex97** [comment]
no, the tile size remains the same as the standard. The registration_xy_stride and z_stride I used the default value.

**Comment by cgoina** [comment]
try to use '--aff_scale s4'. It looks like the global registration fails and that might be because your volume is really big compared to our test data and even at s3 is very large so let's try to do the global (affine) registration at a smaller scale s4 or even s5.

**Comment by cgoina** [comment]
I don't know exactly what is going on.
How big is your volume? Can you paste the attributes.json from `/fsx/work/outputs/dr2_sap2_r3/stitching/export.n5/c3/s3`

**Comment by cgoina** [comment]
Can you try what @wangyuhan01 suggests in #29
