### ISSUE TITLE
Glitch in measure_intensity

### ISSUE THREAD

**Issue by FangmingXie** [JaneliaSciComp/multifish#34]
## Description of the problem

I tried running multifish on an in-house generated large-scale one-round dataset. To avoid memory issue, I segmented the volume using "s3" resolution on DAPI channel. I was able to get the segmentation mask (tif file), but ran into an error in `measure_intensity`.

```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'measure_intensities (3)'
      raise ValueError('Label and intensity image must have the'
  ValueError: Label and intensity image must have the same shape.
```

Upon checking, I believe this is a glitch in `measure_intensity`, where it did not use the correct resolution (now s3 instead of s2 by default) to pull stitched images. Indeed I saw the error is caused by the following command in the log, which sets the scale as "s2" instead of the correct one "s3".
```
python /app/scripts/intensity_measurements.py /u/scratch/f/f7xiesnm/p28nr2_sap3/outputs/r3/segmentation/r3-c3.tif /u/scratch/f/f7xiesnm/p28nr2_sap3/outputs/r3/stitching/export.n5 /u/scratch/f/f7xiesnm/p28nr2_sap3/outputs/r3/intensities r3 c2 s2 c3 c1
```

Could you help me resolve this glitch? I am now using `main.nf` for everything and passing parameters using a json file.

## Log file(s)

Happy to provide more.

### Environment 

* EASI-FISH Pipeline version: this early May pulled from Github
* Nextflow version: 22.10.07
* Container runtime: Singularity
* Platform: Local
* Operating system: Linux - CentOS

**Comment by wangyuhan01** [comment]
Hi Fangming, sorry to hear that you ran into issues with pipeline. You could try this step on your local workstation with [the python code](https://github.com/JaneliaSciComp/multifish/blob/master/containers/spot_assignment/scripts/python/intensity_measurements.py). You should be able to pass the scale of the image with the cmd you posted. But before you do that, I would check the segmentation result with s3 as our segmentation model is trained on s2 scale images. It would be helpful to confirm the segmentation is reasonable before proceeding. I hope this helps.

**Comment by cgoina** [comment]
measure_intensity uses the same scale as the deformation scale. So if for your local alignment you used s2 that what the intensities uses  and it assumes that the deformation and the segmentation used the same scale. So you can try to run your deformation at s3 as well and maybe run the local affine alignment at s4

**Comment by FangmingXie** [comment]
@wangyuhan01 Thanks! This makes sense.

@cgoina Ah, I suspect this is the reason too, thanks for letting me know! However, here I am running everything with one-round data, with no registration involved. So I guess `measure_intensity` should always use the resolution of segmentation to get intensity, at least in this case?

**Comment by FangmingXie** [comment]
Thanks @cgoina! No rush. Meanwhile I can use your trick to get things through on my end. I will just make sure `def_scale` is always the same as `segmentation_scale`.
