### ISSUE TITLE
Segmentation_memory for large sample

### ISSUE THREAD

**Issue by FangmingXie** [JaneliaSciComp/multifish#35]
## Description of the problem

I have a question about `segmentation_memory`. In particular, when I run a large-scale in-house generated data, I ran into this error below using the default `segmentation_scale=s2`. The issue is resolved if I change this to `s3` just to get things through, but according to @wangyuhan01 this is not ideal.
```
May-19 12:54:31.412 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'segmentation:predict (1)'
  MemoryError: Unable to allocate 118. GiB for an array with shape (429, 1122, 685, 96) and data type float32
```

I ran this on a computing node with ~80G memory in total. It is possible to request more memory but it will take much longer wait time to get the job run. Is there a way to limit the size of the image for segmentation? My understanding of the pipeline as of now is that it first reads in the full image volume and then call StarDist. Can we control the size of the image volume that runs through StarDist? 

Many thanks!

## Log file(s)

Happy to provide more.

### Environment 

* EASI-FISH Pipeline version: May, 2023
* Nextflow version: 22.10.7
* Container runtime: Singularity
* Platform: Local
* Operating system: Linux - CentOS

**Comment by cgoina** [comment]
there's a parameter that lets you set the memory available for the segmentation process: '--segmentation_memory'. For the small dataset is 20G, if not set it defaults to 220G but this is the memory that it can be made available to the container provided that the computer has that much memory. So in your case you need to run it on a computer that has at least 120GB since it requires to allocate 118GB

**Comment by FangmingXie** [comment]
@cgoina I have set this `segmentation_memory` to be 60G, but it still ran into error. Do you know why?

**Comment by cgoina** [comment]
@FangmingXie it says it needs 118GB so you really need to allocate at least that much - unfortunatelly at this point the segmentation cannot be split in smaller jobs but it is on our todo list

**Comment by FangmingXie** [comment]
@cgoina Thanks no worries! I totally understand this is a work in progress. I just wanted to understand how it is working now, and to find ways around it.

So it looks like `segmentation_memory` specifies how much memory will be allocated to the container, instead of controlling the size of the image volume that will be read into the memory. Is that correct?

Also, is this memory demand mostly from reading the full image volume into memory? Say if we have a smaller sample, or crop the images we collected into smaller pieces, this issue will in principle go away?

Thanks!

**Comment by cgoina** [comment]
@FangmingXie that's correct the memory requirement is because the entire volume must fit in the internal memory and it depends only on the size of the volume. Smaller volumes will use smaller memory - that's why segmentation works at s3 but not s2 - the s3.size = 1/8 * s2.size.

**Comment by FangmingXie** [comment]
@cgoina Got it thanks! This makes sense.
