### ISSUE TITLE
Memory calculation

### ISSUE THREAD

**Issue by FangmingXie** [JaneliaSciComp/multifish#36]
I wanted to ask a question, rather than reporting a bug. 

(Is here a good place to ask question? Please let me know if this is not...)

In Spark powered applications such as `stitching` and `spot_extraction` using RS-FISH, these parameters set how much resources the application requests from the server per acquisition:
- `workers`
- `worker_cores`
- `gb_per_core`
- `driver_cores`
- `driver_memory`

How do those parameters relate to the total number of cores and memory? Below is my guess based on my running experience and reading the docs. 
- `total_mem = N_acq * (workers * worker_cores * gb_per_core + driver_cores * driver_memory)`
- `total_cores = N_acq * (workers * worker_cores + driver_cores)`

where `N_acq` is the number of acquisition. 

My questions:
- Is this understanding correct?
- What does `N_acq` mean in different contexts? I guess in stitching, this is the number of imaging rounds. In spot extraction, this is the number of FISH channels * the number of imaging rounds? In other words, all spot channels are processed together in parallel?
- Will other processes (segmentation, registration) run in parallel to RS-FISH, such that the total resource demand is even higher than the above calculation?

Many thanks!

**Comment by krokicki** [comment]
Hi @FangmingXie,

1) Your equations are correct. 
2) The number of acquisitions is always the number of imaging rounds. RS-FISH works the same way as stitching: we create a transient spark cluster for every acquisition, and those all process in parallel. I'm not sure exactly how much parallel processing is going on within the Spark cluster, I haven't looked into that code. But that's a moot point for your equations, the cluster size is still calculated the same way. Note that there are separate parameters which control these cluster sizes (e.g. "rsfish_workers" vs "workers" for stitching) so the two steps can have different clusters, but they are arranged the same way.
3) Yes, all steps in the pipeline will run as soon as a) their input data is ready and b) there are available resources. 

Let me know if that answers your questions or if there is anything else I can clarify.

**Comment by FangmingXie** [comment]
@krokicki Thanks this makes sense and is very helpful. I will need to use this to plan out the max resources I need to request from our cluster.
