### ISSUE TITLE
Poor registration result

### ISSUE THREAD

**Issue by JienaL** [JaneliaSciComp/multifish#37]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

## Description of the problem

(A clear and concise description of the nature of issue.)
Two-round data were analyzed in the pipeline while the registration result looks poor. Global alignment seems does not work. Why would this happened and how to change parameters to improve this result? Here are some images.

a. Fixed in green, moving in red (before alignment).
![image](https://github.com/JaneliaSciComp/multifish/assets/133867732/95d6e4d5-281d-43ad-8f41-1ff1700eab02)

b. Fixed in green, global aligned in red.
![image](https://github.com/JaneliaSciComp/multifish/assets/133867732/05efe022-0f39-49dc-8a44-242f3045248e)

c. Fixed in green, global + local aligned in red.
![image](https://github.com/JaneliaSciComp/multifish/assets/133867732/9b033c13-124f-4037-9aef-862079cb02e8)

## Log file(s)

(Please attach relevant log files, including .nextflow.log and any process logs that had errors.)

### Environment 

* EASI-FISH Pipeline version: [?] 
* Nextflow version: [?]
* Container runtime: [e.g. Docker, Singularity]
* Platform: [e.g. Local, LSF, AWS Batch with Tower, etc.]
* Operating system: [Linux, macOS, etc]

### Additional context

(Add any other context about the problem here)

**Comment by JienaL** [comment]
This is the parameter that I use:
 "registration_xy_stride":1024,  "registration_z_stride":128. Others are defaults.

**Comment by GFleishman** [comment]
Hi Jiena - glad we are working this issue out via email together. Please follow up with the log files I need to determine why the global alignment did not work. We have already determined that spot detection for both the fixed and moving images worked well. This is most likely easy to correct by changing a few parameters for the global affine alignment. But to determine which parameters to change, I would like to see the log files that Konrad showed you how to find in our email thread.
