### ISSUE TITLE
Error at registration:moving_spots

### ISSUE THREAD

**Issue by bradleycolquitt** [JaneliaSciComp/multifish#5]
## Description of the problem

I'm receiving an error during registration:moving_spots. A few tasks succeed but several fail.

The input files are two rounds of 3x5 tiles but with differing number of slices. The fixed round has 1285 slices and the moving round has 200 slices. 

We've been troubleshooting some issues with our lightsheet, which has led to inconsistent slice numbers for each round. This could be the source of our problem right there, but I wanted to get your input on this.

## Log file(s)

[nextflow.log](https://github.com/JaneliaSciComp/multifish/files/7543310/nextflow.log)
Command log from one of the failed processes [command.log](https://github.com/JaneliaSciComp/multifish/files/7543320/command.log)

### Environment 

* EASI-FISH Pipeline version: [?] 
* Nextflow version: 20.10.0.5430

* Container runtime: Singularity

* Platform: SGE
* Operating system: Linux

**Comment by cgoina** [comment]
I forwarded this to the author of the registration package. The moment we find out more or if we need some more logs from you we will let you know.

**Comment by cgoina** [comment]
How many channels are in each round?

**Comment by bradleycolquitt** [comment]
Thanks. 4 channels.

**Comment by wangyuhan01** [comment]
Sorry I just saw this issue, but It looks to me that the registration pipeline failed to detect enough features (spots) from the moving round for RANSAC affine based on the error message. 

```
pruned_spots = prune_blobs(sortedSpots, overlap, min_distance)[:,:-2].astype(np.int)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

Is there a chance that the image from moving round has different signal intensity? It is also possible if this error appears after global affine, that some image chunks from moving round has no signal due to the drastic difference in z-slice number. Current registration pipeline requires the fix and moving image in similar size (x,y dimension and z slice).

**Comment by bradleycolquitt** [comment]
Great thanks. I'm getting a similar error for two rounds that are closer in dimension than the images I recieved the original error with. Round 1 (fixed) has 800 slices and Round 2 (moving) has 919 slices. I've also tried the reverse (Round 2 fixed, Round 1 moving) and got the same error. Would you recommend subsetting round 2 to 800 slices?

**Comment by wangyuhan01** [comment]
It does not seem to me that the difference in z-slice is the problem, especially you have tried registration both ways. Does either round have very poor SNR? These are purely my guesses, but an empty block/chunk could also cause this issue.
