### ISSUE TITLE
demo_tiny.sh error in spot extraction step

### ISSUE THREAD

**Issue by KMSmichelle** [JaneliaSciComp/multifish#9]
Hi, I ran this "./examples/demo_tiny.sh work", and get the below error, which i dont understand what causing this error. Please help, thanks!

## Bug report 
Error executing process > 'spot_extraction:airlocalize:run_airlocalize (3)'

Caused by:
  Process `spot_extraction:airlocalize:run_airlocalize (3)` terminated with an error exit status (255)

Command executed:

  export SCRATCH_DIR=$PROCESS_DIR
  echo "SCRATCH_DIR: $SCRATCH_DIR"
  echo "/app/airlocalize/airlocalize.sh /mnt/volume1/multifish/multifish/work/outputs/LHA3_R3_tiny/stitching/export.n5 /c0/s0 /mnt/volume1/multifish/multifish/work/outputs/LHA3_R3_tiny/spots/tiles/2/coords.txt /app/airlocalize/params/air_localize_default_params.txt /mnt/volume1/multifish/multifish/work/outputs/LHA3_R3_tiny/spots/tiles/2 _c0.txt"
  /app/airlocalize/airlocalize.sh /mnt/volume1/multifish/multifish/work/outputs/LHA3_R3_tiny/stitching/export.n5 /c0/s0 /mnt/volume1/multifish/multifish/work/outputs/LHA3_R3_tiny/spots/tiles/2/coords.txt /app/airlocalize/params/air_localize_default_params.txt /mnt/volume1/multifish/multifish/work/outputs/LHA3_R3_tiny/spots/tiles/2 _c0.txt

Command exit status:
  255

Command output:
  (empty)

Command error:
  INFO:    Could not find any nv files on this host!
  INFO:    Converting SIF file to temporary sandbox...
  FATAL:   while extracting /home/ubuntu/.singularity_cache/public.ecr.aws-janeliascicomp-multifish-spot_extraction-1.1.0.img: root filesystem extraction failed: failed to copy content in staging file: write /tmp/rootfs-258799536/archive-055744335: no space left on device

Work dir:
  /mnt/volume1/multifish/multifish/work/fc/5da63703c5e208ed61739e78c05cbc

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
(Please follow this template replacing the text between parentheses with the requested information)

## Description of the problem

(A clear and concise description of the nature of issue.)

## Log file(s)

(Please attach relevant log files, including .nextflow.log and any process logs that had errors.)

### Environment 

* EASI-FISH Pipeline version: [2.2.0] 
* Nextflow version: [21.10.6]
* Container runtime: [ Singularity]
* Platform: [RONIN/AWS]
* Operating system: [Linux]
256 GiB RAM  32 vCPUs
### Additional context

(Add any other context about the problem here)

**Comment by krokicki** [comment]
Hi @KMSmichelle,

This issue is described on the troubleshooting page: https://janeliascicomp.github.io/multifish/Troubleshooting.html

Basically, the pipeline needs additional temporary space to build Singularity containers. You'll need to set SINGULARITY_TMPDIR to somewhere with more disk space. 

Just a guess, but this might work if you put it in the "Pre-run script" when resuming your pipeline:
`export SINGULARITY_TMPDIR=/mnt/volume1/multifish/multifish/work/`

**Comment by KMSmichelle** [comment]
Hi @krokicki , thanks alot again!
i have tried the suggested code "SINGULARITY_TMPDIR=/mnt/volume1/multifish/multifish/work/ ./examples/demo_tiny.sh work", but it still end up the error with the default temp dir, which contains not enough disk space. Therefore, i created a machine with larger resources, this issue is no more exist. 
But i met another error at segmentation step:
Error executing process > 'segmentation:predict (1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name public.ecr.aws-janeliascicomp-multifish-segmentation-1.0.0.img.pulling.1644503201901 docker://public.ecr.aws/janeliascicomp/multifish/segmentation:1.0.0 > /dev/null
  status : 255
  message:
    INFO:    Converting OCI blobs to SIF format
    INFO:    Starting build...
    Getting image source signatures
    Copying blob sha256:7a0437f04f83f084b7ed68ad9c4a4947e12fc4e1b006b38129bac89114ec3621
    Copying blob sha256:844213a896429b06073d1c75fa83dcc2e80c1be937c314177b06ad0c1c2e474d
    Copying blob sha256:959d67f29bc4442fb6ee1bffd10e98e04bf21280a3c99df4badd98a651b7c678
    Copying blob sha256:166cb76694d5eda4e2f39e46525b4a81096a71bd1ba6427052a3aaf418cd97cc
    Copying blob sha256:c95be90039432bdfe9deb4f9eb5126e2e08bc29bbfa7876cf2ebdc0bfa22c8d3
    Copying blob sha256:fe2127ab93529c2b9afa42bf025b1d82fa8796af9b3722ccf657987364fb9338
    Copying blob sha256:74958507df405d53a7dfeae4842a3b2565aec211a613b8b5669de59475b1a0f5
    Copying blob sha256:f4fe5997b42060d49ef28be6cda1de73a0276815d65cbc74a56e06f92fef953e
    Copying blob sha256:154dc1fea78758affbc74e4588e8b022bb2ddd91fc4f82d863619f535d62d495
    Copying config sha256:1a3a55d80193ff55c1cb29451d9dbe83ccf5116f38b775ab8e6fdb6ea286c95e
    Writing manifest to image destination
    Storing signatures
    2022/02/10 14:36:28  info unpack layer: sha256:7a0437f04f83f084b7ed68ad9c4a4947e12fc4e1b006b38129bac89114ec3621
    2022/02/10 14:36:28  warn rootless{usr/bin/newgidmap} ignoring (usually) harmless EPERM on setxattr "security.capability"
    2022/02/10 14:36:28  warn rootless{usr/bin/newuidmap} ignoring (usually) harmless EPERM on setxattr "security.capability"
    2022/02/10 14:36:28  warn rootless{usr/bin/ping} ignoring (usually) harmless EPERM on setxattr "security.capability"
    2022/02/10 14:36:30  warn rootless{usr/sbin/arping} ignoring (usually) harmless EPERM on setxattr "security.capability"
    2022/02/10 14:36:30  warn rootless{usr/sbin/clockdiff} ignoring (usually) harmless EPERM on setxattr "security.capability"
    2022/02/10 14:36:30  info unpack layer: sha256:844213a896429b06073d1c75fa83dcc2e80c1be937c314177b06ad0c1c2e474d
    2022/02/10 14:36:31  warn rootless{usr/bin/staprun} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
    2022/02/10 14:36:35  warn rootless{usr/libexec/openssh/ssh-keysign} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
    2022/02/10 14:36:38  info unpack layer: sha256:959d67f29bc4442fb6ee1bffd10e98e04bf21280a3c99df4badd98a651b7c678
    2022/02/10 14:36:42  info unpack layer: sha256:166cb76694d5eda4e2f39e46525b4a81096a71bd1ba6427052a3aaf418cd97cc
    2022/02/10 14:36:42  info unpack layer: sha256:c95be90039432bdfe9deb4f9eb5126e2e08bc29bbfa7876cf2ebdc0bfa22c8d3
    2022/02/10 14:36:42  info unpack layer: sha256:fe2127ab93529c2b9afa42bf025b1d82fa8796af9b3722ccf657987364fb9338
    2022/02/10 14:36:42  info unpack layer: sha256:74958507df405d53a7dfeae4842a3b2565aec211a613b8b5669de59475b1a0f5
    2022/02/10 14:36:42  info unpack layer: sha256:f4fe5997b42060d49ef28be6cda1de73a0276815d65cbc74a56e06f92fef953e
    2022/02/10 14:36:45  info unpack layer: sha256:154dc1fea78758affbc74e4588e8b022bb2ddd91fc4f82d863619f535d62d495
    INFO:    Creating SIF file...
    FATAL:   While making image from oci registry: error copying image out of cache: could not copy file: write tmp-copy-439632110: no space left on device

I checked the disk usage, there is space on root and working directory:
(multifish_conda) ubuntu@ip-10-0-7-179:/mnt/volume1/multifish$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             94G     0   94G   0% /dev
tmpfs            19G  924K   19G   1% /run
/dev/nvme1n1p1   97G   68G   30G  70% /
tmpfs            94G     0   94G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            94G     0   94G   0% /sys/fs/cgroup
/dev/loop0       13M   13M     0 100% /snap/amazon-ssm-agent/495
/dev/loop1       88M   88M     0 100% /snap/core/5328
/dev/nvme0n1p1  246G  6.0G  227G   3% /mnt/volume1
/dev/loop2      111M  111M     0 100% /snap/core/12603
tmpfs            19G     0   19G   0% /run/user/1000
/dev/loop3       56M   56M     0 100% /snap/core18/2284
/dev/loop4       25M   25M     0 100% /snap/amazon-ssm-agent/4046

Please advice.
Thank you.

**Comment by krokicki** [comment]
Sorry, I somehow didn't catch that you are using examples/demo_tiny.sh. If you look inside that script, it sets up all the relevant temporary directories based on the TMPDIR variable. Also, I'm not sure if it will work with a relative path for the data dir, you should use the absolute path. Please give this a try:

`TMPDIR=/mnt/volume1/multifish/multifish/work ./examples/demo_tiny.sh /mnt/volume1/multifish/multifish/work`

**Comment by KMSmichelle** [comment]
Hi @krokicki ,

thanks again for all the suggestions, I have tested all, unfortunately none of them works for me. The TMPDIR is still sticking to the default home/ubuntu.

**Comment by krokicki** [comment]
Hi @KMSmichelle, just wanted to make sure you saw the fix above.

**Comment by KMSmichelle** [comment]
Hi @Konrad ***@***.***>,

Thanks for helping, I couldn’t fix the problem.
I found the python code for segmentation works for me, so I use the segmentation code for my works.

Best regards,
Michelle
